# Generated by Django 4.0.4 on 2022-05-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='ImageField',
            new_name='image',
        ),
    ]
